spring:
  profiles:
    include: [common]
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.244.9.82:3306/ly_novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: hongfeng123456
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 2
    minIdle: 5
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    maxEvictableIdleTimeMillis: 180000
    phyTimeoutMillis: 15000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开removeAbandoned功能 设置一个连接的租期，如果超过removeAbandonedTimeout时间直接清除连接
    removeAbandoned: true
    # 1800秒，也就是30分钟
    removeAbandonedTimeout: 1800
    # 关闭abanded连接时输出错误日志
    logAbandoned: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: config.decrypt=true;druid.log.conn=false;druid.log.stmt=false;druid.log.rs=false;druid.log.stmt.executableSql=true;
    # druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
pic:
  save:
    type: 1 #图片保存方式, 1不保存，使用网络图片 ，2本地保存
    path: /app/ly/data/img  #图片保存路径




