spring:
  profiles:
    include: [common]
  datasource:
    url: jdbc:mysql://47.244.9.82:3306/ly_novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: hongfeng123456
    driver-class-name: com.mysql.cj.jdbc.Driver


pic:
  save:
    type: 2  #图片保存方式, 1不保存，使用网络图片 ，2本地保存
    path: /app/ly/data/img  #图片保存路径



